#version
version: "3.8"

#services
services:
  backend:
    build:
      context: /home/prithvi/Desktop/CICD/simple_app
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    stdin_open: true
    tty: true
